version: '3'
services:
  bstack:
    build:
      context: .
    working_dir: /home/pwn
    container_name: one-gadget-rce
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9007:9000"
    entrypoint: /etc/init.sh
