version: '3'

services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "30001:80"
    restart: "always"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - ./html:/usr/share/nginx/html

