version: '3'

services:
  php:
    container_name: php_apache
    build: ./php
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    ports:
      - 8080:80
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=Wani_12007_3b438b701305bc53c8f208b0eeda95cc7ae4ae7b
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=wani
      - MYSQL_PASSWORD=waniwani