version: '3'

services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "30001:80"
    restart: "always"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "./js/:/static/"

  php-fpm:
    image: "php:8.0.0rc1-fpm-alpine"
    volumes:
      - "./php/:/var/www/html/"
